### ISSUE TITLE
"Redirect Admin Default Register Page"

### ISSUE THREAD

**Issue by laranz** [AyeCode/uwp-social#39]
Bug or feature?

When we keep this option unchecked, "Redirect Admin Default Register Page" and still it takes us to the userswp's registration page?

**Comment by wpdev10** [comment]
We use a filter 'register_url' for changing the register page URL which is used on the wp-admin and on the frontend too. So due to this filter, the register link is changed on the wp-admin login form but the purpose of the "Redirect Admin Default Register Page" is to allow always redirect to our register page, and if not then one should remove the register page from our settings which will then not redirect on frontend or backend to our registration page. So disabling this will only disable redirect if one login from the /wp-login.php?action=register. Let me know if any questions.
